config/routes.rb
Rails.application.routes.draw do
  get 'items_planner/index'
  get 'orders/index'

  root 'home#index'

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :items
  resources :kitchen do
    patch :update_status, on: :member
    patch :update_status_item, on: :member
    patch :whoops, on: :member
  end
  resources :reports
  resources :tables
  resources :close_and_open do
    patch :update_status, on: :member
  end
  resources :orders
  resources :ingredients
  resources :items_planner do
    get :getIngredients, on: :collection
  end
  resources :inventory

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    attr_accessor :average
    attr_accessor :sales
    attr_accessor :available_qty
    attr_accessor :status
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/orders_item.rb
class OrdersItem < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.order("id ASC").all
  end

  def new
    @ingredients = Ingredient.all
    @item = Item.new
  end

  def create
    @params = item_params
    @item = Item.new(@params.except('recipe'))
    if @item.save
      JSON.parse(@params[:recipe]).each do |ingredient|
        Recipe.create(id_item: @item.id, id_ingredient: ingredient['id'], quantity: ingredient['value'])
      end
      redirect_to '/items'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def update
    @ingredients = Ingredient.all
    if @item.update(item_params)
      redirect_to '/items'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, status: :see_other
  end

  def edit
  end

  private
  def item_params
    params.require(:item).permit(:name, :price, :category, :image, :recipe)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @items = Item.all
    @tables = Table.all
    @orders = Order.select("DISTINCT ON (tables_id) *").order("tables_id, created_at DESC")
    @category = params[:category]
    @input = params[:name]
    @order = (Order.count + 1) unless (@order = params[:order])

    @products = if @input
                  Item.where('name ILIKE ?', "%#{@input}%")
                elsif @category.present?
                  if @category === 'all'
                    Item.all
                  else
                    Item.where('category ILIKE ?', "%#{@category}%")
                  end

                else
                  Item.all
                end
  end

  def create
    items = params[:order]
    total = params[:total]
    note = params[:note]
    mesa = params[:selected_table_id]
    number_order = params[:numberOrder]

    if number_order
      newOrder = Order.find(number_order)
      newOrder.total += total
      newOrder.status = 'wait'
      newOrder.note += "\n #{note}"
      newOrder.save
    else
      newOrder = Order.create(
        tables_id: mesa,
        status: 'wait',
        total: total,
        note: note
      )
      number_order = newOrder.id
    end

    items.each do |item|
      id = Item.find_by(name: item[:name]).id
      OrdersItem.create(order_id: number_order, item_id: id, quantity: item[:quantity])
      ingredients = Recipe.all.where(id_item: id)
      ingredients.each do |ingredientRecipe|
        ingredient = Ingredient.find(ingredientRecipe.id_ingredient)
        ingredient.total -=  ingredientRecipe.quantity * item[:quantity]
        ingredient.total = 0 if ingredient.total < 0
        ingredient.save
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/items_planner_helper.rb
module ItemsPlannerHelper
end

app/helpers/kitchen_helper.rb
module KitchenHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/shared/_footer.html.erb
<footer class='footer__container'>
    <div>
      <a href='/'>
        <%= image_tag 'svg/foodpoint.svg', size: '60x60' %>
      </a>
    </div>

    <div>
      <p>Política de Privacidad - Política de Cookies</p>
    </div>

    <div>
      <a href='https://github.com/BrightCoders-Institute/BCDIC22-RoR-proyecto-final-team3'>
        <img class='footer__media' src="https://img.icons8.com/ios-glyphs/30/4a8ebf/github.png"/>
      </a>
      <img class='footer__media' src="https://img.icons8.com/ios-glyphs/30/4a8ebf/facebook-new.png"/>
      <img class='footer__media' src="https://img.icons8.com/ios-glyphs/30/4a8ebf/twitter--v1.png"/>
      <img class='footer__media' src="https://img.icons8.com/ios-glyphs/30/4a8ebf/linkedin.png"/>
      <img class='footer__media' src="https://img.icons8.com/ios-glyphs/30/4a8ebf/instagram-new.png"/>
      <img class='footer__media' src="https://img.icons8.com/ios-glyphs/30/4a8ebf/tiktok.png"/>
      <img class='footer__media' src="https://img.icons8.com/ios-glyphs/30/4a8ebf/snapchat.png"/>
    </div>
</footer>

app/views/shared/_navbarAdmin.html.erb
<div>
  <%=  javascript_include_tag 'navbar' %>
  <div id="mySidenav" class="navbar__container">
    <a class="navbar__close__btn" onclick="closeNav()">&times;</a>
    <%= image_tag("1.png", class:'navbar__logo')%>
    <div class='navbar__menu' >
      <%= link_to 'Tables', tables_path, class: 'navbar__menu__option'%>
      <%= link_to 'Items', items_path, class: 'navbar__menu__option'%>
      <%= link_to 'Reports', reports_path, class: 'navbar__menu__option'%>
      <%= link_to 'Ingredients', ingredients_path, class: 'navbar__menu__option'%>
      <%= link_to 'Items planner', items_planner_index_path, class: 'navbar__menu__option'%>
      <%= link_to 'Inventory', inventory_index_path, class: 'navbar__menu__option'%>
    </div>
    <div class="flex-shrink-0">
      <div class='navbar__logout' >
        <%= link_to 'Log Out', destroy_user_session_path, class: "navbar__logout__option",:method => 'delete' %>
      </div>
    </div>
    <div id='main' class="navbar__container__closed" onclick="openNav()">
      <%= image_tag("1.png", class:'navbar__logo__closed', id:'logo')%>
    </div>
  </div>
</div>

app/views/shared/_navbarService.html.erb
<div>
  <%=  javascript_include_tag 'navbarService' %>
  <div id="mySidenavService" class="navbar__container">
    <a class="navbar__close__btn" onclick="closeNav()">&times;</a>
    <%= image_tag("1.png", class:'navbar__logo')%>
    <div class='navbar__menu' >
      <%= link_to 'Kitchen', kitchen_index_path, class: 'navbar__menu__option'%>
      <%= link_to 'Service', orders_path, class: 'navbar__menu__option'%>
      <%= link_to 'Orders', close_and_open_index_path, class: 'navbar__menu__option'%>
    </div>
    <div class="flex-shrink-0">
      <div class='navbar__logout' >
        <%= link_to 'Home', root_path, class: "navbar__logout__option"%>
      </div>
    </div>
    <div id='mainService' class="navbar__container__closed" onclick="openNav()">
      <%= image_tag("1.png", class:'navbar__logo__closed', id:'logoService')%>
    </div>
  </div>
</div>

app/views/shared/_supplies_modal.html.erb
<%= render 'shared/navbarAdmin' %>
<div class="modal">
  <div class="modal-content">
    <div class="header-modal">
      <h1 class="title">Ingredients to supply!</h1>
      <h1 class="close">X</h1>
    </div>
    <div class="main-modal">
      <div class="table-container">
        <div class="tittle-main-modal">
          <h1>Ingredients</h1>
        </div>
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Req. Sup.</th>
              <th>Unit Price</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody class="modal-supply">
            <% @ingSupplieList.each do |ingredient| %>
              <tr class="ingredient">
                <td><%= ingredient[:id] %></td>
                <td><%= ingredient[:name] %></td>
                <td><%= ingredient[:reqSupp] %><%= ingredient[:units] == 'grams' ? ' gr' : ' mil'%></td>
                <td>$<%= ingredient[:price] %></td>
                <td>$<%= ingredient[:total].round(0) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <h1>Total: $<%= @ingSupplieList.reduce(0) { |sum, ingredient| sum + ingredient[:total] }.round(0) %></h1>
      </div>
    </div>
  </div>
</div>