config/routes.rb
Rails.application.routes.draw do
  get 'items_planner/index'
  get 'orders/index'

  root 'home#index'

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :items
  resources :kitchen do
    patch :update_status, on: :member
    patch :update_status_item, on: :member
    patch :whoops, on: :member
  end
  resources :reports
  resources :tables
  resources :close_and_open do
    patch :update_status, on: :member
  end
  resources :orders
  resources :ingredients
  resources :items_planner do
    get :getIngredients, on: :collection
  end
  resources :inventory

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    attr_accessor :average
    attr_accessor :sales
    attr_accessor :available_qty
    attr_accessor :status
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/orders_item.rb
class OrdersItem < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.order("id ASC").all
  end

  def new
    @ingredients = Ingredient.all
    @item = Item.new
  end

  def create
    @params = item_params
    @item = Item.new(@params.except('recipe'))
    if @item.save
      JSON.parse(@params[:recipe]).each do |ingredient|
        Recipe.create(id_item: @item.id, id_ingredient: ingredient['id'], quantity: ingredient['value'])
      end
      redirect_to '/items'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def update
    @ingredients = Ingredient.all
    if @item.update(item_params)
      redirect_to '/items'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, status: :see_other
  end

  def edit
  end

  private
  def item_params
    params.require(:item).permit(:name, :price, :category, :image, :recipe)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @items = Item.all
    @tables = Table.all
    @orders = Order.select("DISTINCT ON (tables_id) *").order("tables_id, created_at DESC")
    @category = params[:category]
    @input = params[:name]
    @order = (Order.count + 1) unless (@order = params[:order])

    @products = if @input
                  Item.where('name ILIKE ?', "%#{@input}%")
                elsif @category.present?
                  if @category === 'all'
                    Item.all
                  else
                    Item.where('category ILIKE ?', "%#{@category}%")
                  end

                else
                  Item.all
                end
  end

  def create
    items = params[:order]
    total = params[:total]
    note = params[:note]
    mesa = params[:selected_table_id]
    number_order = params[:numberOrder]

    if number_order
      newOrder = Order.find(number_order)
      newOrder.total += total
      newOrder.status = 'wait'
      newOrder.note += "\n #{note}"
      newOrder.save
    else
      newOrder = Order.create(
        tables_id: mesa,
        status: 'wait',
        total: total,
        note: note
      )
      number_order = newOrder.id
    end

    items.each do |item|
      id = Item.find_by(name: item[:name]).id
      OrdersItem.create(order_id: number_order, item_id: id, quantity: item[:quantity])
      ingredients = Recipe.all.where(id_item: id)
      ingredients.each do |ingredientRecipe|
        ingredient = Ingredient.find(ingredientRecipe.id_ingredient)
        ingredient.total -=  ingredientRecipe.quantity * item[:quantity]
        ingredient.total = 0 if ingredient.total < 0
        ingredient.save
      end
    end
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  def index
    @tables = Table.all
  end

  def new
    @table = Table.new
  end

  def create
    @table = Table.new(table_params)
    if @table.save
      redirect_to '/tables'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def update
    if @table.update(table_params)
      redirect_to '/tables'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @table.destroy
    redirect_to tables_path, status: :see_other
  end

  def edit
  end

  private
  def table_params
    params.require(:table).permit(:name, :size)
  end

  def set_table
    @table = Table.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/close_and_open_helper.rb
module CloseAndOpenHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/items_planner_helper.rb
module ItemsPlannerHelper
end

app/helpers/kitchen_helper.rb
module KitchenHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/home/index.html.erb
<div class="main-container">
  <div class="left-container">
    <div class="text-container">
      <p>Handmade,
        with an Extra
        Pinch of Love </p>
    </div>
  </div>
  <div class="rigth-container">
    <%=image_tag("svg/foodpoint.svg")%>
    <div class="buttons-container">
      <%= link_to kitchen_index_path  do %>
        <button class="button-home">
          <p>Kitchen</p>
          <span><%= image_tag("restaurant_menu_white_24dp.svg")%> </span>  </button>
      <% end %>
      <%= link_to orders_path do %>
        <button class="button-home">
          <p>Service</p>
          <span><%= image_tag("supervisor_account_white_24dp.svg")%> </span>  </button>
      <% end %>
      <%= link_to items_path do %>
        <button class="button-home">
          <p>Admin</p>
          <span><%= image_tag("support_agent_white_24dp.svg")%> </span>  </button>
      <% end %>
    </div>
  </div>
</div>

app/views/tables/_form.html.erb
<%= form_with model: @table do |form| %>
  <div class="info-container">
    <%= form.text_field :name, :required => true, placeholder: "Name" %>
  </div>
  <div class="info-container">
    <%= form.text_field :size, :required => true, placeholder: "Size" %>
  </div>
  <div class="button-container">
    <%= form.submit %>
    <%= link_to tables_path do %>
      <button>Cancel</button>
    <% end %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<div class="two-container">
  <div class="image-container1">
      <%=image_tag("svg/foodpoint.svg")%>  
  </div>
  <div class="register-container">
    <div class="register"> 
      <%=image_tag("svg/edit.svg")%>  
      <div class="title-container">
        <h1>Edit table!</h1>
      </div>
      <div class="form-container">
        <%= render "form", employee: @table %>
      </div>
    </div>
  </div>
</div>

app/views/tables/index.html.erb
<%= render 'shared/navbarAdmin' %>
<div class="main-container">
  <div class="table-container">
    <div class="tittle-container">
      <h1>Tables</h1>
      <%= link_to new_table_path do %>
        <button>+ New table</button>
      <% end %>
    </div>
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Size</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @tables.each do |table| %>
          <tr>
            <td><%= table.id %></td>
            <td><%= table.name %></td>
            <td><%= table.size %></td>
            <td>
            <%= link_to edit_table_path(table) do%>
              <button class="edit-button">Edit</button>
            <% end %>

            <%= link_to table_path(table), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
              } do 
            %>
              <button class="delete-button" >X</button>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/tables/new.html.erb
<div class="two-container">
  <div class="image-container2">
      <%=image_tag("svg/foodpoint.svg")%>  
  </div>
  <div class="register-container">
    <div class="register"> 
      <%=image_tag("svg/new.svg")%>  
      <div class="title-container">
        <h1>New table!</h1>
      </div>
      <div class="form-container">
        <%= render "form", employee: @table %>
      </div>
    </div>
  </div>
</div>