config/routes.rb
Rails.application.routes.draw do
  get 'items_planner/index'
  get 'orders/index'

  root 'home#index'

  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :items
  resources :kitchen do
    patch :update_status, on: :member
    patch :update_status_item, on: :member
    patch :whoops, on: :member
  end
  resources :reports
  resources :tables
  resources :close_and_open do
    patch :update_status, on: :member
  end
  resources :orders
  resources :ingredients
  resources :items_planner do
    get :getIngredients, on: :collection
  end
  resources :inventory

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
    has_one_attached :image
    attr_accessor :average
    attr_accessor :sales
    attr_accessor :available_qty
    attr_accessor :status
end

app/models/order.rb
class Order < ApplicationRecord
end

app/models/orders_item.rb
class OrdersItem < ApplicationRecord
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/table.rb
class Table < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  def index
    @items = Item.order("id ASC").all
  end

  def new
    @ingredients = Ingredient.all
    @item = Item.new
  end

  def create
    @params = item_params
    @item = Item.new(@params.except('recipe'))
    if @item.save
      JSON.parse(@params[:recipe]).each do |ingredient|
        Recipe.create(id_item: @item.id, id_ingredient: ingredient['id'], quantity: ingredient['value'])
      end
      redirect_to '/items'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def update
    @ingredients = Ingredient.all
    if @item.update(item_params)
      redirect_to '/items'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, status: :see_other
  end

  def edit
  end

  private
  def item_params
    params.require(:item).permit(:name, :price, :category, :image, :recipe)
  end

  def set_item
    @item = Item.find(params[:id])
  end
end

app/controllers/kitchen_controller.rb
class KitchenController < ApplicationController
  helper_method :statusTextBtn
  helper_method :statuscolor
  helper_method :statusColorOverlay

  def index
    @ordersN = Order.
      select("
        orders.id as order_id, orders.status, orders.note,
        tables.name as table, tables.id as table_id, items.id as item_id,
        items.name as item,
        orders_items.quantity, orders_items.status_item, orders_items.id as orders_items_id").
      joins("
        JOIN orders_items ON orders.id = orders_items.order_id
        JOIN tables ON orders.tables_id = tables.id
        JOIN items ON orders_items.item_id = items.id").
        order("orders.status ASC, orders.created_at ASC")

  end



  def update_status
    order = Order.find(params[:id])
    if order.status == 'wait'
      order.update(status: 'progress')
    elsif order.status == 'progress'
      order.update(status: 'done')
      finished(order)
    elsif order.status == 'done'
      order.update(status: 'closed')
    end
    redirect_to kitchen_index_path
  end

  def finished(order)
    orderitems = OrdersItem.where(order_id: order)
    orderitems.update_all(status_item: true)
  end

  def whoops
    order = Order.find(params[:id])
    order.update(status: 'progress')
    redirect_to kitchen_index_path
  end


  def update_status_item
    orderitems = OrdersItem.find(params[:id])
    if orderitems.status_item == false
      orderitems.update(status_item: true)
    elsif orderitems.status_item == true
      orderitems.update(status_item: false)
    end
    redirect_to kitchen_index_path
  end



  def statuscolor(status)
    if status == 'wait'
      'status_waiting'
    elsif status == 'progress'
      'status_progress'
    elsif status == 'done'
      'status_done'
    end
  end


  def statusColorOverlay(status)
    if status == 'wait'
      'status_waiting_overlay'
    elsif status == 'progress'
      'status_progress_overlay'
    elsif status == 'done'
      'status_done_overlay'
    end
  end

  def statusTextBtn(status)
    if status == 'wait'
      'Mark as working'
    elsif status == 'progress'
      'Mark as Done'
    elsif status == 'done'
      'Close'
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :verify_authenticity_token
  def index
    @items = Item.all
    @tables = Table.all
    @orders = Order.select("DISTINCT ON (tables_id) *").order("tables_id, created_at DESC")
    @category = params[:category]
    @input = params[:name]
    @order = (Order.count + 1) unless (@order = params[:order])

    @products = if @input
                  Item.where('name ILIKE ?', "%#{@input}%")
                elsif @category.present?
                  if @category === 'all'
                    Item.all
                  else
                    Item.where('category ILIKE ?', "%#{@category}%")
                  end

                else
                  Item.all
                end
  end

  def create
    items = params[:order]
    total = params[:total]
    note = params[:note]
    mesa = params[:selected_table_id]
    number_order = params[:numberOrder]

    if number_order
      newOrder = Order.find(number_order)
      newOrder.total += total
      newOrder.status = 'wait'
      newOrder.note += "\n #{note}"
      newOrder.save
    else
      newOrder = Order.create(
        tables_id: mesa,
        status: 'wait',
        total: total,
        note: note
      )
      number_order = newOrder.id
    end

    items.each do |item|
      id = Item.find_by(name: item[:name]).id
      OrdersItem.create(order_id: number_order, item_id: id, quantity: item[:quantity])
      ingredients = Recipe.all.where(id_item: id)
      ingredients.each do |ingredientRecipe|
        ingredient = Ingredient.find(ingredientRecipe.id_ingredient)
        ingredient.total -=  ingredientRecipe.quantity * item[:quantity]
        ingredient.total = 0 if ingredient.total < 0
        ingredient.save
      end
    end
  end
end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_table, only: [:show, :edit, :update, :destroy]

  def index
    @tables = Table.all
  end

  def new
    @table = Table.new
  end

  def create
    @table = Table.new(table_params)
    if @table.save
      redirect_to '/tables'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def update
    if @table.update(table_params)
      redirect_to '/tables'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @table.destroy
    redirect_to tables_path, status: :see_other
  end

  def edit
  end

  private
  def table_params
    params.require(:table).permit(:name, :size)
  end

  def set_table
    @table = Table.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/close_and_open_helper.rb
module CloseAndOpenHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/items_planner_helper.rb
module ItemsPlannerHelper
end

app/helpers/kitchen_helper.rb
module KitchenHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/items/_create_form.html.erb
<%= form_with(model: @item, html: { class: "form" }) do |form| %>
  <div class="info-container">
    <%= form.text_field :name, :required => true, placeholder: "Name" %>
  </div>
  <div class="info-container">
    <%= form.number_field :price, :required => true, placeholder: "Price" %>
  </div>
  <div class="info-container">
    <%= form.select :category, ["Food", "Dessert", "Drink"] %>  
  </div>
  <div class="info-container">
    <%= form.file_field :image, :required => true, placeholder: "Image", class: "file-select"%>
  </div>
  <div class="info-container">
      <%= form.hidden_field :recipe, value: "" %>
  </div>
  <div class="button-container">
    <div class="info-container">
      <div class="recipe">Create item</div>
    </div>
    <%= link_to items_path do %>
      <button>Cancel</button>
    <% end %>
  </div>
<% end %>
<%=  javascript_include_tag 'recipe-modal' %>

app/views/items/_edit_form.html.erb
<%= form_with model: @item do |form| %>
  <div class="info-container">
    <%= form.text_field :name, :required => true, placeholder: "Name" %>
  </div>
  <div class="info-container">
    <%= form.number_field :price, :required => true, placeholder: "Price" %>
  </div>
  <div class="info-container">
    <%= form.select :category, ["Food", "Dessert", "Drink"] %>  
  </div>
  <div class="info-container">
    <%= form.file_field :image, placeholder: "Image", class: "file-select"%>
  </div>
  <div class="button-container">
    <%= form.submit %>
    <%= link_to items_path do %>
      <button>Cancel</button>
    <% end %>
  </div>
<% end %>
<%=  javascript_include_tag 'recipe-modal' %>

app/views/items/_form.html.erb
<%= form_with model: @item do |form| %>
  <div class="info-container">
    <%= form.text_field :name, :required => true, placeholder: "Name" %>
  </div>
  <div class="info-container">
    <%= form.number_field :price, :required => true, placeholder: "Price" %>
  </div>
  <div class="info-container">
    <%= form.select :category, ["Starter", "Main", "Drink", "Dessert"] %>  
  </div>
  <div class="info-container">
    <%= form.file_field :image, :required => true, placeholder: "Image", class: "file-select"%>
  </div>
  <div class="info-container">
    <div class="recipe">Create recipe</div>
  </div>
  <div class="button-container">
    <%= form.submit %>
    <%= link_to items_path do %>
      <button>Cancel</button>
    <% end %>
  </div>
<% end %>
<%=  javascript_include_tag 'recipe-modal' %>

app/views/items/_modal.html.erb
<div class="modal">
  <div class="modal-content">
    <div class="header-modal">
      <h1 class="title">Make recipe for <span class="dish"></span>!</h1>
      <h1 class="close">X</h1>
    </div>
    <div class="main-modal">
      <div class="table-container">
        <div class="tittle-main-modal">
          <h1>Select ingredients</h1>
        </div>
        <table>
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Price</th>
              <th>Units</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            <% @ingredients.each do |ingredient| %>
              <tr class="ingredient">
                <td class="id-ing"><%= ingredient.id %></td>
                <td class="name-ing"><%= ingredient.name %></td>
                <td>$<span class="price-ing"><%= ingredient.price %></span></td>
                <td class="units-ing"><%= ingredient.quant %></td>
                <td>
                  <button class="add-button">Add</button>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="table-container">
        <div class="tittle-main-modal">
          <h1>Recipe</h1>
        </div>
        <h1 class="alert">
            No ingredients
        </h1>
        <table class="recipe-table">
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Quant.</th>
              <th>Price</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody class="recipe-tbody">
          </tbody>
        </table>
        <div class="prices-recipe">
          <h1>Total price:&nbsp &nbsp  &nbsp &nbsp &nbsp$<span class="prices-total">0</span></h1>
          <h1>Suggested price: &nbsp $<span class="suggest-total">0</span></h1>
        </div>
        <div class="button-container">
          <button class="button-recipe">Create recipe!</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/items/create.html.erb
<h1>Tables#create</h1>
<p>Find me in app/views/tables/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Tables#destroy</h1>
<p>Find me in app/views/tables/destroy.html.erb</p>

app/views/items/edit.html.erb
<div class="two-container">
  <div class="image-container1">
      <%=image_tag("svg/foodpoint.svg")%>  
  </div>
  <div class="register-container">
    <div class="register"> 
      <%=image_tag("svg/edit.svg")%>  
      <div class="title-container">
        <h1>Edit item!</h1>
      </div>
      <div class="form-container">
        <%= render "edit_form", item: @item %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<%= render 'shared/navbarAdmin' %>
<div class="main-container">
  <div class="table-container">
    <div class="tittle-container">
      <h1>Items</h1>
      <%= link_to new_item_path do %>
        <button>+ New item</button>
      <% end %>
    </div>
    <table>
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Price</th>
          <th>Category</th>
          <th>Image</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= item.name %></td>
            <td><%= item.price %></td>
            <td><%= item.category %></td>
            <td><%= image_tag item.image, class: "image-display" %></td>
            <td>
            <%= link_to edit_item_path(item) do%>
              <button class="edit-button">Edit</button>
            <% end %>

            <%= link_to item_path(item), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
              } do


            %>
              <button class="delete-button" >X</button>
            <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/items/new.html.erb
<%= render "modal" %>
<div class="two-container">
  <div class="image-container2">
      <%=image_tag("svg/foodpoint.svg")%>  
  </div>
  <div class="register-container">
    <div class="register"> 
      <%=image_tag("svg/new.svg")%>  
      <div class="title-container">
        <h1>New item!</h1>
      </div>
      <div class="form-container">
        <%= render "create_form", item: @item %>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<h1>Tables#show</h1>
<p>Find me in app/views/tables/show.html.erb</p>

app/views/items/update.html.erb
<h1>Tables#update</h1>
<p>Find me in app/views/tables/update.html.erb</p>